name: ${APP_NAME}
services:
  mnemos_ai:
    container_name: ${APP_NAME}
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres
    image: postgres:17.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    restart: unless-stopped
    volumes:
      - ${PATH_TO_CREATE_DB_FILE}:/docker-entrypoint-initdb.d # Здесь умерло 25 бомжей, которых пинали 25 ежей. Занавес.
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost" ]
      interval: 2s
      timeout: 10s
      retries: 5
